version: '3'

services:
  db:
    container_name: db
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "default_db"
    volumes:
      - postgresdata:/var/lib/postgresql/data

  elasticsearch:
    container_name: es
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.1
    environment:
      - cluster.name=test-cluster-elasticsearch
      - transport.host=localhost
    ports:
    - 9200:9200
    - 9300:9300
    depends_on:
      - db
    volumes:
    - esdata:/usr/share/elasticsearch/data
#  elasticsearch:
#    container_name: es
#    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.1
#    environment:
#      - cluster.name=joxi-cluster-elasticsearch
#      - transport.host=localhost
#      - cluster.name=docker-cluster
#      - bootstrap.memory_lock=true
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#    depends_on:
#      - db
#    volumes:
#      - esdata:/usr/share/elasticsearch/data

  rabbitmq:
    container_name: rammitmq
    hostname: 'rammitmq'
    image: rabbitmq:3.7.18
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq/mnesia/
    environment:
        RABBITMQ_DEFAULT_USER: user
        RABBITMQ_DEFAULT_PASS: password

  django:
    container_name: django
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./myapp:/app
    ports:
      - 8000:8000
    depends_on:
      - db
      - rabbitmq
      - redis
    links:
      - db
#      - elasticsearch
      - rabbitmq
      - redis

  celery:
    container_name: celery
    build: .
    command: celery -A myapp worker -l info
    volumes:
      - ./myapp:/app
    depends_on:
      - db
      - rabbitmq
      - django
      - redis
    links:
      - db
#      - elasticsearch
      - rabbitmq
      - redis

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379

volumes:
  postgresdata:
  rabbitmqdata:
  esdata:
