# Generated by Django 4.1 on 2022-08-12 09:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user_id', models.IntegerField()),
                ('video_id', models.CharField(max_length=255)),
            ],
        ),
    ]
