# Generated by Django 4.1 on 2022-08-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_category_id_alter_tag_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
